name: setin
description: Setting Screen Flutter Playground.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  bloc: ^8.1.0
  go_router: ^4.5.1
  minimize_app: ^0.1.1
  provider: ^6.0.3
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.9

flutter:
  uses-material-design: true
  fonts:
    - family: InterTight
      fonts:
        - asset: assets/fonts/inter_tight_regular.ttf
          weight: 400
        - asset: assets/fonts/inter_tight_semi_bold.ttf
          weight: 600

  assets:
    - assets/images/

flutter_native_splash:
  image: "assets/images/splash_logo.png"
  color: "#FFFFFF"